language: php

php:  5.6


before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - cp .env.travis .env
  - cp /config/doctrine.travis.php /config/doctrine.php
  - mysql -e 'create database notosplus;'
  - ./vendor/bin/doctrine orm:schema-tool:create

script:
  - phpunit