language: php

php:  5.6


before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - cp .env.travis .env
  - mysql -e 'create database notosplus;'
  - php vendor/bin/doctrine schema:update

script:
  - phpunit